### ISSUE TITLE
"Process completed with exit code 3."

### ISSUE THREAD

**Issue by sajith** [1Password/check-signed-commits-action#7]
Thank you for creating and publishing this action.  We've been using this rather uneventfully, until recently when a PR with a single signed commit did not pass muster. 

The action did not leave a comment on the PR or exit with 1.  From a glance at `curl -s https://api.github.com/repos/fabric-testbed/fabrictestbed-extensions/pulls/268/commits`, GitHub API response has the expected `commit.verification.verified == true` bit.

Example:

https://github.com/fabric-testbed/fabrictestbed-extensions/actions/runs/7390336594/

What could be going on here?

**Comment by florisvdg** [comment]
Thanks for reporting! Looking at the logs you linked, it seems that GitHub doesn't set `github.event.pull_request.commits_url`. That's likely to be because you've configured your workflow to also run on `push`. This action is currently only intended to run on [`pull_request` or `pull_request_target`](https://github.com/1Password/check-signed-commits-action?tab=readme-ov-file#pull_request_target-vs-pull_request).

**Comment by sajith** [comment]
Thank you. That makes sense, and it turns out that I did not bother to read the documentation. :^)

Sorry about the noise!
